### ISSUE TITLE
Black images!

### ISSUE THREAD

**Issue by Archilla1** [OnlineHacKing/CameraHack#5]
Hi!!!! 

 So far this tool has been one of the easiest to use! The only thing I noticed is that the images takes are show black once I go to the folder to look at them. I tried with 2 different phones and same issue. Help!

**Comment by Bgidgenkk** [comment]
How do I send the request to the other phone?

**Comment by Bgidgenkk** [comment]
[Look at this shit](live/liveYTTV.html#L2) #2
